### ISSUE TITLE
Warning with datas sensibillity

### ISSUE THREAD

**Issue by DanielDavidDev** [isaacmeira/SeniorChallenge#2]
# Warning

[Database](https://github.com/isaacmeira/SeniorChallenge/blob/925ffc6676ed3c5690fc3266672e9ad6a5bb641d/Back/src/config/database.js)

Cuidado com dados sensíveis.

**Comment by isaacmeira** [comment]
sim, geralmente escondo estes dados, porém esse foi um teste para uma empresa, dai não era necessário, mas obrigado pela dica =)
